# Generated by Django 5.0.1 on 2024-01-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pcode', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mfd', models.DateField()),
                ('exp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdiscount', models.CharField(max_length=200)),
            ],
        ),
    ]
