# Generated by Django 5.0.1 on 2024-01-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_rename_pname_productdiscount_prodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
