# Generated by Django 5.0.1 on 2024-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0007_rename_disount_product_disount_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disount_per',
            field=models.IntegerField(default=0),
        ),
    ]
