# Generated by Django 5.0.1 on 2024-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0008_alter_product_disount_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disount_per',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_per',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_count',
            field=models.CharField(default=0),
        ),
    ]
