# Generated by Django 5.0.1 on 2024-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('price', models.FloatField()),
                ('waranty', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('product_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
