# Generated by Django 5.0.1 on 2024-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_alter_module_phone_no_alter_module_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pcode', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('original_price', models.CharField(max_length=100)),
                ('new_price', models.CharField(default=0, max_length=100)),
                ('disount_per', models.IntegerField(default=0)),
                ('mfd', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=20)),
                ('prod_count', models.IntegerField(default=0)),
            ],
        ),
    ]
