# Generated by Django 5.0.1 on 2024-01-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disount_per',
            new_name='discount_per',
        ),
    ]
