# Generated by Django 5.0.1 on 2024-02-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_alter_product_discount_per'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
