# Generated by Django 4.2.10 on 2024-02-13 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_soldproducts_delete_soldproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2024, 2, 13, 10, 22, 22, 377386), max_length=200),
        ),
    ]
