# Generated by Django 4.2.10 on 2024-02-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2024, 2, 18, 11, 56, 44, 901604), max_length=200),
        ),
    ]
