# Generated by Django 4.2.7 on 2024-03-05 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2024, 3, 5, 11, 48, 45, 400369), max_length=200),
        ),
    ]
