# Generated by Django 4.2.7 on 2024-03-24 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2024, 3, 24, 10, 56, 22, 605824), max_length=200),
        ),
    ]
