# Generated by Django 5.0.1 on 2024-01-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbackmodel',
            new_name='feedbacktable',
        ),
    ]
