# Generated by Django 5.0.1 on 2024-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_rename_feedbacktable_feedbacktables'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktables',
            name='feed_back',
            field=models.TextField(default='text', max_length=1000),
        ),
        migrations.AddField(
            model_name='feedbacktables',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
